conversion_count_settings:
    bam: "/mnt/gauss/storage1/home/hendgert/data/compoundScreen/bulk/exp2/compound_bulk_exp2.filtered.Aligned.GeneTagged.sorted.bam" # Path to input bam file.
    gtf: "/mnt/gauss/storage1/home/hendgert/resources/annotations/human/Homo_sapiens.GRCh38.95.chr.gtf" # Path to GTF file, should be the same as the one used to generate the input bam file
    name: "exp2" # Prefix for file names
    procs: 30  # Number of concurrent processes
    cutoff: 100000 # Number of reads per cell to use for calculating cell stats. Default: 100000
    qual: 30 # Quality cutoff
    sub: 1.0 # Float for subsampling of data
    bc: "data/indices_used.txt" # Path to list of barcodes to use
    pc_calc: 'pc' # Can be pc or no_pc
    seq_layout: 'paired_end' # can be single_end or paired_end
    
MCMC_runner_settings:
    num_iters: 10000 # Number of iterations before restarting the inference.
    num_procs: 30 # Number of concurrent processes to use for MCMC inference
    outfolder: "data" # Path to outfolder
    max_files: 500000 # Maximum number of files per output folder

cleanup_settings:
    base_path: "data"
    num_procs: 30
    handle_folders: "remove"
